### PR TITLE
Logs and raises error when Sparql Writer post fails. Composite ETL co…

### LINKED ISSUE #292: Sparql Writer should check for and handle errors
The Sparql Writer currently catches and logs StandardErrors. However, it should also check for a successful HTTP response and raise an error when it occurs.

Composite ETL should handle the error. The loader CLI should leave the error uncaught.

### PR DESCRIPTION
**Pull request by justinlittman**
…ntinues on Sparql Writer error.

closes #292

### CODE REVIEW

File: lib/rialto/etl/writers/sparql_writer.rb [hunk 1]
```diff
@@ -102,11 +102,13 @@ def send_batch(batch)
         # Post the statements to the SPARQL endpoint
         # @param [String] SPARQL statements to send
         def post(statements)
-          client.post do |req|
+          response = client.post do |req|
             req.body = statements
           end
+          raise "#{response.reason_phrase}: #{response.status}  (#{response.body})" unless response.success?
```
Comment (jcoyne) [inline lib/rialto/etl/writers/sparql_writer.rb]: can you add a test for this behavior?

Comment (justinlittman) [reply lib/rialto/etl/writers/sparql_writer.rb]: Or better yet, can I write any tests for Sparql Writer ...

Comment (justinlittman) [reply lib/rialto/etl/writers/sparql_writer.rb]: @jcoyne Test added.

Comment (jcoyne) [reply lib/rialto/etl/writers/sparql_writer.rb]: For some reason SparqlWriter#close() is not getting called in our test suite (which is what cause the coverage to fall).  Is that expected?

Comment (justinlittman) [reply lib/rialto/etl/writers/sparql_writer.rb]: Added a test for close.

File: spec/writers/sparql_writer_spec.rb [hunk 2]
```diff
@@ -0,0 +1,90 @@
+# frozen_string_literal: true
+
+require 'traject'
+require 'rialto/etl/writers/sparql_writer'
+
+RSpec.describe Rialto::Etl::Writers::SparqlWriter do
+  subject(:writer) do
+    described_class.new(
+      'sparql_writer.update_url': 'http://127.0.0.1:9999/sparql',
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: Are you writing the args this way because Traject wants symbol Hash keys? If so, OK. If not, and if Traject is OK with string Hash keys, it would look a little more idiomatic to use `'foo.bar' => 'http...'` rather than `'foo.bar': 'http...'`.

File: spec/writers/sparql_writer_spec.rb [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+    allow(logger).to receive(:info)
+    allow(logger).to receive(:debug)
+  end
+
+  describe '#put' do
+    let(:batch) do
+      Traject::Indexer::Context.new(source_record: 'SPARQL INSERT STATEMENT')
+    end
+
+    describe 'when returns 200' do
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: Would you consider `s/describe/context/` here?

File: spec/writers/sparql_writer_spec.rb [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+            }
+          )
+          .to_return(status: 200, body: '', headers: {})
+      end
+
+      it 'posts the statement' do
+        writer.put(batch)
+      end
+    end
+    describe 'when returns 500' do
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: Would you consider `s/describe/context/` here?

File: spec/writers/sparql_writer_spec.rb [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+            body: 'SPARQL INSERT STATEMENT',
+            headers: {
+              'Content-Type' => 'application/sparql-update; charset=utf-8'
+            }
+          )
+          .to_return(status: 200, body: '', headers: {})
+      end
+
+      it 'posts the statement' do
+        writer.put(batch)
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: Do you need an expectation of some sort here? I'm not sure what's being tested here.

Comment (mjgiarlo) [reply spec/writers/sparql_writer_spec.rb]: Like, expect not to raise error, expect not to log a warning, etc.

File: spec/writers/sparql_writer_spec.rb [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+          .to_return(status: 500, body: '', headers: {})
+      end
+
+      it 'raises an error' do
+        expect { writer.put(batch) }.to raise_error(RuntimeError)
+        expect(logger).to have_received(:warn).with('Error in SPARQL update. : 500  () (RuntimeError)')
+      end
+    end
+    describe '#close' do
+      let(:batch) do
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: The `let` statement looks identical to the one above. Could consider pulling it into the containing context?

File: spec/writers/sparql_writer_spec.rb [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+        Traject::Indexer::Context.new(source_record: 'SPARQL INSERT STATEMENT')
+      end
+
+      let(:batch_size) { 2 }
+
+      describe 'when returns 200' do
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: Would you consider `s/describe/context/` here?

File: spec/writers/sparql_writer_spec.rb [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+        before do
+          stub_request(:post, 'http://127.0.0.1:9999/sparql')
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: There's a bunch of repeated code here, if my eyes don't fail me. Could consider pulling this `before` block to the containing context and just customize the bit(s) that need varying using `let` blocks. Looks like that'd be the status?

File: spec/writers/sparql_writer_spec.rb [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+              body: 'SPARQL INSERT STATEMENT',
+              headers: {
+                'Content-Type' => 'application/sparql-update; charset=utf-8'
+              }
+            )
+            .to_return(status: 200, body: '', headers: {})
+        end
+
+        it 'posts the statement' do
+          writer.put(batch)
```
Comment (mjgiarlo) [inline spec/writers/sparql_writer_spec.rb]: Not seeing any expectations here either.

File: spec/writers/sparql_writer_spec.rb (hunk 2 above)
Comment (justinlittman) [reply spec/writers/sparql_writer_spec.rb]: Right, Ruby idioms not python ... Fixing.
