### PR TITLE
Handles missing or null grant agency.

### LINKED ISSUE #368: WOS fetch_grant_agencies error
On staging processing `data/wos_2017-10-01+2017-12-31.ndj`:

```
Traceback (most recent call last): 
        19: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `blo
ck in create_worker'
        18: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `cat
ch'
        17: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
        16: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
        15: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
        14: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
        13: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/thread_pool.rb:123:in `block in maybe_in_thread_pool'
        12: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:554:in `block (3 levels) in process'
        11: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:429:in `map_to_context!'
        10: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:429:in `each'
         9: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:435:in `block in map_to_context!'
         8: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:476:in `handle_mapping_errors'
         7: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer.rb:436:in `block (2 levels) in map_to_context!'
         6: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer/step.rb:135:in `execute'
         5: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer/step.rb:135:in `each'
         4: from /opt/app/rialto/rialto/shared/bundle/ruby/2.5.0/gems/traject-3.0.0/lib/traject/indexer/step.rb:138:in `block in execute'
         3: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:211:in `block (2 levels) in load_config_file'
         2: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:56:in `fetch_grant_agencies'
         1: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:56:in `map'
lib/rialto/etl/configs/wos_to_sparql_statements.rb:57:in `block in fetch_grant_agencies': undefined method `empty?' for nil:NilClass (NoMethodError)
```

### PR DESCRIPTION
**Pull request by justinlittman**
closes #368

### CODE REVIEW

File: lib/rialto/etl/configs/wos_to_sparql_statements.rb [hunk 1]
```diff
@@ -54,8 +54,9 @@ def parse_address(addr)
 # Find the grant agencies
 def fetch_grant_agencies(json)
   agencies = Array.wrap(JsonPath.on(json, '$.static_data.fullrecord_metadata.fund_ack.grants.grant').first).map do |grant|
-    next if grant.fetch('grant_agency', []).empty?
-    grant['grant_agency']
+    grant_agency = grant['grant_agency']
```
Comment (mjgiarlo) [inline lib/rialto/etl/configs/wos_to_sparql_statements.rb]: I believe we have ActiveSupport required in this context, so we could make use of `#blank?` and reduce this to:

```ruby
next if grant['grant_agency'].blank?
```

What's here now is a-ok, too.
